# Generated by Django 4.1.2 on 2022-11-01 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('date_added',)},
        ),
    ]
